metric:
  name: acc
  goal: max
parameters:
    model:
        values: ["resnet18",
              "vgg11_bn"]
    epochs:
        values: [2]
    optimizer:
        values: ["Adam"]
    lr:
        values: [0.0001]
    aug:
        values: [False]


    task = Task.create(project_name='clearLM_sweep'
                    ,task_name='Pytorch cifar base'
                    ,add_task_init_call=True
                    ,script="/Work30/kitagawatomoki/pytorch_cifar10/base_template_cifar10.py"
                    )