metric:
  name: acc
  goal: max
parameters:
    model:
        values: ["resnet18",
              "vgg11_bn"]
    epochs:
        values: [2]
    optimizer:
        values: ["Adam"]
    lr:
        values: [0.0001]
    aug:
        values: [False]